'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useRouter } from 'next/navigation';
import AdminNavbar from '@/components/AdminNavbar';
import {
    Users,
    Search,
    Loader2,
    Shield,
    CheckCircle2
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

import { Database } from '@/lib/database.types';

export default function UsersListPage() {
    const [loading, setLoading] = useState(true);
    const [profiles, setProfiles] = useState<Database['public']['Tables']['profiles']['Row'][]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [updatingId, setUpdatingId] = useState<string | null>(null);

    const router = useRouter();
    const supabase = createClient();

    const fetchProfiles = async () => {
        try {
            const { data, error } = await supabase
                .from('profiles')
                .select('*')
                .order('updated_at', { ascending: false });

            if (error) throw error;
            setProfiles(data || []);
        } catch (err) {
            console.error("Error fetching profiles:", err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchProfiles();
    }, []);



    const toggleAdminStatus = async (id: string, currentStatus: boolean) => {
        setUpdatingId(id);
        try {
            const { error } = await supabase
                .from('profiles')
                // @ts-expect-error type generated by CLI hasn't fully propagated or handles booleans strictly
                .update({ is_admin: !currentStatus })
                .eq('id', id);

            if (error) throw error;
            setProfiles(prev => prev.map(p => p.id === id ? { ...p, is_admin: !currentStatus } : p));
        } catch (err) {
            console.error("Error updating Admin status:", err);
            alert("Failed to update Admin status. Please try again.");
        } finally {
            setUpdatingId(null);
        }
    };

    const filteredProfiles = profiles.filter(profile =>
        (profile.full_name?.toLowerCase() || '').includes(searchQuery.toLowerCase()) ||
        (profile.organization?.toLowerCase() || '').includes(searchQuery.toLowerCase())
    );

    return (
        <div className="min-h-screen bg-[#F8FAFC]">
            <AdminNavbar />

            <main className="pl-64 pr-10 pt-10 pb-20">
                <header className="flex items-center justify-between mb-12">
                    <div>
                        <h1 className="text-4xl font-black text-slate-900 tracking-tight leading-none mb-3">User Management</h1>
                        <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">Manage all registered users and assign BDM tags</p>
                    </div>
                </header>

                {/* Search Bar */}
                <div className="relative mb-10 group">
                    <Search className="absolute left-6 top-1/2 -translate-y-1/2 h-6 w-6 text-slate-300 group-focus-within:text-blue-500 transition-colors" />
                    <input
                        type="text"
                        placeholder="Search by name or organization..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full bg-white border border-slate-100 rounded-[32px] py-6 pl-16 pr-8 outline-none focus:border-blue-600 transition-all font-bold text-slate-900 shadow-sm focus:shadow-xl focus:shadow-blue-900/5 placeholder:text-slate-300"
                    />
                </div>

                {loading ? (
                    <div className="flex justify-center py-20">
                        <Loader2 className="h-10 w-10 text-blue-600 animate-spin" />
                    </div>
                ) : profiles.length === 0 ? (
                    <div className="bg-white rounded-[48px] p-20 text-center border border-slate-100 border-dashed">
                        <div className="h-20 w-20 bg-slate-50 rounded-full flex items-center justify-center text-slate-200 mx-auto mb-6">
                            <Users className="h-10 w-10" />
                        </div>
                        <h3 className="text-xl font-black text-slate-900 mb-2">No users found</h3>
                        <p className="text-slate-400 font-bold mb-8">There are currently no registered users.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        <AnimatePresence mode="popLayout">
                            {filteredProfiles.map((profile) => (
                                <motion.div
                                    key={profile.id}
                                    layout
                                    initial={{ opacity: 0, scale: 0.9 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 0.9 }}
                                    transition={{ duration: 0.3 }}
                                    className="bg-white rounded-[40px] p-8 shadow-sm border border-slate-100 relative overflow-hidden group hover:shadow-2xl hover:shadow-slate-200/50 transition-all duration-500 flex flex-col"
                                >
                                    <div className="flex items-start justify-between mb-4">
                                        <div className="h-16 w-16 rounded-[24px] bg-gradient-to-br from-blue-500 to-indigo-600 p-[2px] shadow-sm">
                                            <div className="h-full w-full rounded-[22px] bg-white flex items-center justify-center overflow-hidden">
                                                <img src={`https://ui-avatars.com/api/?name=${profile.full_name || 'User'}&background=fff&color=3b82f6`} alt="Avatar" />
                                            </div>
                                        </div>
                                        <div className="flex flex-col gap-2">
                                            {profile.is_admin && (
                                                <span className="bg-slate-900 text-white px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest text-center">
                                                    Admin
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    <h3 className="text-xl font-black text-slate-900 mb-1 leading-tight">{profile.full_name || 'Unknown User'}</h3>
                                    <p className="text-sm font-bold text-slate-400 mb-6">{profile.organization || 'No Organization'}</p>

                                    <div className="mt-auto pt-6 border-t border-slate-50 flex flex-col gap-4">
                                        {/* Admin Switch */}
                                        <div className="flex items-center justify-between">
                                            <div className="flex flex-col">
                                                <span className="text-sm font-black text-slate-900">Admin Privileges</span>
                                                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">System Access</span>
                                            </div>
                                            <button
                                                onClick={() => toggleAdminStatus(profile.id, !!profile.is_admin)}
                                                disabled={updatingId === profile.id}
                                                className={`relative inline-flex h-7 w-12 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${profile.is_admin ? 'bg-slate-900' : 'bg-slate-200'} disabled:opacity-50`}
                                            >
                                                <span className="sr-only">Toggle Admin status</span>
                                                <span
                                                    className={`pointer-events-none inline-block h-6 w-6 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${profile.is_admin ? 'translate-x-5' : 'translate-x-0'}`}
                                                />
                                            </button>
                                        </div>
                                    </div>
                                </motion.div>
                            ))}
                        </AnimatePresence>
                    </div>
                )}
            </main>
        </div>
    );
}
